const CATALOG_IMAGE_BASE = "https://res.cloudinary.com/silns2x1/image/upload/redveg/catalog/";

const brandedCatalogFiles: Record<string, string> = {
  "Desi Mutton": "Desi_Mutton.png",
  "Rewaji Mutton": "Rewaji_Mutton.png",
  "Mutton Keema": "Mutton_Keema.png",
  "Mutton Liver": "Mutton_Liver.png",
  "Chicken Curry Cut": "Chicken_Curry_Cut.png",
  "Chicken Leg Side": "Chicken_Leg_Side.png",
  "Chicken Drumsticks": "Chicken_Drumsticks.png",
  "Boneless Chicken": "Boneless_Chicken.png",
  "Chicken With Skin": "Chicken_With_Skin.png",
  "Deshi Chicken": "Deshi_Chicken.png",
  "Chicken Liver": "Chicken_Liver.png",
  "Chapra Chingri": "Chapra_Chingri.png",
  "Golda Chingri": "Golda_Chingri.png",
  "Bagda Chingri": "Bagda_Chingri.png",
  "Sundarban Crab": "Sundarban_Crab.png",
  Crab: "Crab.png",
  "Big Crab": "Big_Crab.png",
  Gugli: "Gugli.png",
  "Duck Meat": "Duck_Meat.png",
  "Bangladeshi Hilsa": "Bangladeshi_Hilsa.png",
  "DimWala Hilsha": "DimWala_Hilsha.png",
  "Rui Kata": "Rui_Kata.png",
  "Rui Peti": "Rui_Peti.png",
  "Rui Gota (Whole)": "Rui_Gota_Whole.png",
  "Katla Kata": "Katla_Kata.png",
  "Katla Only Peti": "Katla_Only_Peti.png",
  "Katla Gota": "Katla_Gota.png",
  Pomfret: "Pomfret.png",
  "Bhetki Fish": "Bhetki_Fish.png",
  "Bhetki Fillet (Fish fry)": "Bhetki_Fillet_Fish_fry.png",
  Topse: "Topse.png",
  Kajoli: "Kajoli.png",
  "Aar Fish": "Aar_Fish.png",
  "Boal Kata": "Boal_Kata.png",
  "Aar Fish Big": "Aar_Fish_Big.png",
  Koi: "Koi.png",
  "Janto Tangra": "Janto_Tangra.png",
  Telapia: "Telapia.png",
  Padba: "Padba.png",
  "Lote Fish": "Lote_Fish.png",
  "Bata Fish": "Bata_Fish.png",
  Gule: "Gule.png",
  Pakal: "Pakal.png",
  "Deshi Shol": "Deshi_Shol.png",
  "Deshi Singi": "Deshi_Singi.png",
  "Deshi Magur": "Deshi_Magur.png",
  "Deshi Tangra": "Deshi_Tangra.png",
  "Deshi Parse": "Deshi_Parse.png",
  "Deshi Puti": "Deshi_Puti.png",
  "Fish Egg": "Fish_Egg.png",
};

export function brandedCatalogImage(productName: string | undefined) {
  const fileName = productName ? brandedCatalogFiles[productName.trim()] : undefined;
  return fileName ? `${CATALOG_IMAGE_BASE}${fileName}` : undefined;
}
